/*
Calm Writer - OmmWriter-inspired immersive writing mode for Obsidian.
This file is generated by esbuild. Source: https://github.com/hayato-watanabe/calm-writer
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CalmWriterPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");
var import_view = require("@codemirror/view");

// src/audio/engine.ts
var AudioEngine = class {
  constructor() {
    this.ctx = null;
    this.masterGain = null;
    this.noise = null;
  }
  get context() {
    if (!this.ctx) {
      this.ctx = new AudioContext();
      this.masterGain = this.ctx.createGain();
      this.masterGain.gain.value = 1;
      this.masterGain.connect(this.ctx.destination);
    }
    return this.ctx;
  }
  /** すべての音の出口。タイプ音・BGMはここへつなぐ */
  get output() {
    void this.context;
    return this.masterGain;
  }
  /** ユーザー操作を起点に呼び、サスペンド状態の AudioContext を起こす */
  resume() {
    if (this.ctx && this.ctx.state === "suspended") {
      void this.ctx.resume();
    }
  }
  /**
   * 各シンセで使い回すホワイトノイズバッファ（2秒）。
   * ループ再生時に周期が耳につかないよう、ある程度の長さを確保する。
   */
  get noiseBuffer() {
    const ctx = this.context;
    if (!this.noise) {
      const len = Math.floor(ctx.sampleRate * 2);
      const buf = ctx.createBuffer(1, len, ctx.sampleRate);
      const data = buf.getChannelData(0);
      for (let i = 0; i < len; i++) {
        data[i] = Math.random() * 2 - 1;
      }
      this.noise = buf;
    }
    return this.noise;
  }
  /** 残響用のインパルス応答（指数減衰するステレオノイズ）を生成する */
  createReverbImpulse(seconds = 4, decay = 2.8) {
    const ctx = this.context;
    const len = Math.floor(ctx.sampleRate * seconds);
    const buf = ctx.createBuffer(2, len, ctx.sampleRate);
    for (let ch = 0; ch < 2; ch++) {
      const data = buf.getChannelData(ch);
      for (let i = 0; i < len; i++) {
        data[i] = (Math.random() * 2 - 1) * Math.pow(1 - i / len, decay);
      }
    }
    return buf;
  }
  dispose() {
    if (this.ctx) {
      void this.ctx.close();
      this.ctx = null;
      this.masterGain = null;
      this.noise = null;
    }
  }
};

// src/audio/keySounds.ts
var KEY_SCHEMES = {
  drop: "\u6C34\u6EF4",
  typewriter: "\u30BF\u30A4\u30D7\u30E9\u30A4\u30BF\u30FC",
  marimba: "\u6728\u7434",
  soft: "\u30BD\u30D5\u30C8"
};
var MIN_INTERVAL_MS = 40;
var MARIMBA_SCALE = [
  261.63,
  // ド  C4
  293.66,
  // レ  D4
  329.63,
  // ミ  E4
  349.23,
  // ファ F4
  392,
  //  ソ  G4
  440,
  //  ラ  A4
  493.88,
  // シ  B4
  523.25,
  // ド  C5
  587.33,
  // レ  D5
  659.25
  // ミ  E5
];
var KEY_COLUMNS = {
  Digit1: 0,
  KeyQ: 0,
  KeyA: 0,
  KeyZ: 0,
  Digit2: 1,
  KeyW: 1,
  KeyS: 1,
  KeyX: 1,
  Digit3: 2,
  KeyE: 2,
  KeyD: 2,
  KeyC: 2,
  Digit4: 3,
  KeyR: 3,
  KeyF: 3,
  KeyV: 3,
  Digit5: 4,
  KeyT: 4,
  KeyG: 4,
  KeyB: 4,
  Digit6: 5,
  KeyY: 5,
  KeyH: 5,
  KeyN: 5,
  Digit7: 6,
  KeyU: 6,
  KeyJ: 6,
  KeyM: 6,
  Digit8: 7,
  KeyI: 7,
  KeyK: 7,
  Comma: 7,
  Digit9: 8,
  KeyO: 8,
  KeyL: 8,
  Period: 8,
  Digit0: 9,
  KeyP: 9,
  Semicolon: 9,
  Slash: 9
};
var rand = (a, b) => a + Math.random() * (b - a);
var lerp = (a, b, x) => a + (b - a) * x;
var KeySoundPlayer = class {
  constructor(engine) {
    this.engine = engine;
    this.volume = 0.5;
    // 0..1
    this.scheme = "drop";
    this.lastPlayed = 0;
  }
  /** code = KeyboardEvent.code（木琴が列→音程の割り当てに使う） */
  play(kind, code) {
    const now = performance.now();
    if (now - this.lastPlayed < MIN_INTERVAL_MS) return;
    this.lastPlayed = now;
    const level = this.volume * this.volume * rand(0.8, 1);
    if (level <= 0) return;
    this.engine.resume();
    switch (this.scheme) {
      case "drop":
        this.playDrop(kind, level);
        break;
      case "typewriter":
        this.playTypewriter(kind, level);
        break;
      case "marimba":
        this.playMarimba(kind, level, code);
        break;
      case "soft":
        this.playSoft(kind, level);
        break;
    }
  }
  /**
   * 水滴: 1打ごとに「滴の大きさ」を決め、そこから
   * 音程・長さ・跳ね上がり方・水面の共鳴を連動して変える。
   * 実際の水滴のように、同じ音は二度と鳴らない。
   */
  playDrop(kind, level) {
    const t = this.engine.context.currentTime;
    let size = Math.random();
    let peak = 0.22;
    let freqScale = 1;
    if (kind === "space") {
      size = rand(0.55, 0.85);
      freqScale = 0.62;
    } else if (kind === "enter" || kind === "return") {
      size = rand(0.8, 1);
      freqScale = 0.55;
      peak = 0.26;
    } else if (kind === "delete") {
      size = rand(0, 0.3);
      peak = 0.16;
    }
    const freq = lerp(1050, 480, size) * freqScale * rand(0.92, 1.08);
    const dur = lerp(0.09, 0.3, size) * rand(0.85, 1.15);
    const bend = rand(1.12, 1.75);
    const bendTime = dur * rand(0.45, 0.85);
    this.chirp(t, freq, freq * bend, bendTime, dur, peak * level);
    this.noiseHit(t, rand(2600, 4200), rand(8e-3, 0.02), rand(0.03, 0.07) * level);
    if (size > 0.45) {
      this.thump(t + 5e-3, freq * 0.28, freq * 0.2, dur * 0.8, 0.1 * size * level);
    }
    if (kind === "key" && Math.random() < 0.28) {
      const f2 = freq * rand(1.15, 1.45);
      const d2 = dur * rand(0.5, 0.75);
      this.chirp(t + rand(0.045, 0.09), f2, f2 * rand(1.2, 1.5), d2 * 0.6, d2, peak * 0.4 * level);
    }
  }
  /** タイプライター: ノイズのクリック + 低域のタップ音。確定Enterでベル、改行でキャリッジリターン */
  playTypewriter(kind, level) {
    const t = this.engine.context.currentTime;
    if (kind === "enter") {
      this.tone(t, 1318.5, 0.5, 0.1 * level);
      this.noiseHit(t, 900, 0.05, 0.35 * level, "lowpass");
      this.thump(t, 140, 80, 0.06, 0.3 * level);
    } else if (kind === "return") {
      this.noiseHit(t, 2100, 0.02, 0.32 * level);
      this.noiseSweep(t + 0.03, 1600, 750, 0.12, 0.2 * level);
      this.noiseHit(t + 0.14, 520, 0.06, 0.5 * level, "lowpass");
      this.thump(t + 0.14, 115, 62, 0.09, 0.42 * level);
      this.noiseHit(t + 0.22, 700, 0.03, 0.16 * level, "lowpass");
    } else if (kind === "space") {
      this.noiseHit(t, 1800, 0.025, 0.3 * level);
      this.thump(t, 120, 70, 0.06, 0.35 * level);
    } else if (kind === "delete") {
      this.noiseHit(t, 2e3, 0.02, 0.28 * level);
      this.thump(t, 150, 90, 0.04, 0.2 * level);
    } else {
      this.noiseHit(t, rand(2300, 2900), 0.03, 0.4 * level);
      this.thump(t, 160, 90, 0.05, 0.25 * level);
    }
  }
  /**
   * 木琴: 基音 + 4倍音の短いストライク。
   * キーボードの縦の列ごとに音程が決まり（zの列=ド、xの列=レ…）、鍵盤のように弾ける。
   */
  playMarimba(kind, level, code) {
    let freq;
    let dur = 0.4;
    let peak = 0.22;
    if (kind === "space") {
      freq = 392;
      dur = 0.5;
    } else if (kind === "enter" || kind === "return") {
      freq = 130.81;
      dur = 0.9;
      peak = 0.26;
    } else if (kind === "delete") {
      freq = 220;
      dur = 0.18;
      peak = 0.16;
    } else {
      const column = code !== void 0 ? KEY_COLUMNS[code] : void 0;
      freq = column !== void 0 ? MARIMBA_SCALE[column] : MARIMBA_SCALE[Math.floor(Math.random() * MARIMBA_SCALE.length)];
    }
    freq *= rand(0.998, 1.002);
    const t = this.engine.context.currentTime;
    this.tone(t, freq, dur, peak * level);
    this.tone(t, freq * 4, dur * 0.15, 0.06 * level);
    this.noiseHit(t, 4e3, 8e-3, 0.03 * level);
  }
  /** ソフト: こもったノイズだけの静かなタップ。夜中の執筆向け */
  playSoft(kind, level) {
    const t = this.engine.context.currentTime;
    if (kind === "enter" || kind === "return") {
      this.noiseHit(t, 500, 0.05, 0.4 * level, "lowpass");
      this.thump(t, 130, 80, 0.05, 0.15 * level);
    } else if (kind === "space") {
      this.noiseHit(t, 550, 0.04, 0.38 * level, "lowpass");
    } else if (kind === "delete") {
      this.noiseHit(t, 650, 0.025, 0.3 * level, "lowpass");
    } else {
      this.noiseHit(t, rand(650, 800), 0.03, 0.35 * level, "lowpass");
      this.thump(t, 200, 150, 0.025, 0.08 * level);
    }
  }
  // ---- 部品となるシンセ ----
  /** 一定ピッチのサイン波（指数減衰） */
  tone(t, freq, dur, peak) {
    if (peak <= 0) return;
    const ctx = this.engine.context;
    const osc = ctx.createOscillator();
    osc.type = "sine";
    osc.frequency.value = freq;
    const gain = ctx.createGain();
    gain.gain.setValueAtTime(0, t);
    gain.gain.linearRampToValueAtTime(peak, t + 3e-3);
    gain.gain.exponentialRampToValueAtTime(1e-4, t + dur);
    osc.connect(gain);
    gain.connect(this.engine.output);
    osc.start(t);
    osc.stop(t + dur + 0.05);
  }
  /** ピッチが滑らかに動くサイン波（水滴の「ぴちょん」）。bendTime = ピッチ変化にかける時間 */
  chirp(t, from, to, bendTime, dur, peak) {
    if (peak <= 0) return;
    const ctx = this.engine.context;
    const osc = ctx.createOscillator();
    osc.type = "sine";
    osc.frequency.setValueAtTime(from, t);
    osc.frequency.exponentialRampToValueAtTime(to, t + Math.min(bendTime, dur));
    const gain = ctx.createGain();
    gain.gain.setValueAtTime(0, t);
    gain.gain.linearRampToValueAtTime(peak, t + 3e-3);
    gain.gain.exponentialRampToValueAtTime(1e-4, t + dur);
    osc.connect(gain);
    gain.connect(this.engine.output);
    osc.start(t);
    osc.stop(t + dur + 0.05);
  }
  /** フィルターを通した短いノイズ（クリック・きらめき・タップ） */
  noiseHit(t, freq, dur, peak, type = "bandpass") {
    if (peak <= 0) return;
    const ctx = this.engine.context;
    const src = ctx.createBufferSource();
    src.buffer = this.engine.noiseBuffer;
    const filter = ctx.createBiquadFilter();
    filter.type = type;
    filter.frequency.value = freq;
    filter.Q.value = 1;
    const gain = ctx.createGain();
    gain.gain.setValueAtTime(0, t);
    gain.gain.linearRampToValueAtTime(peak, t + 2e-3);
    gain.gain.exponentialRampToValueAtTime(1e-4, t + Math.max(dur, 0.01));
    src.connect(filter);
    filter.connect(gain);
    gain.connect(this.engine.output);
    src.start(t, Math.random() * 1.5);
    src.stop(t + dur + 0.05);
  }
  /** 中心周波数が滑らかに動くノイズ（キャリッジが滑る「シャーッ」） */
  noiseSweep(t, from, to, dur, peak) {
    if (peak <= 0) return;
    const ctx = this.engine.context;
    const src = ctx.createBufferSource();
    src.buffer = this.engine.noiseBuffer;
    const filter = ctx.createBiquadFilter();
    filter.type = "bandpass";
    filter.frequency.setValueAtTime(from, t);
    filter.frequency.exponentialRampToValueAtTime(to, t + dur);
    filter.Q.value = 1.2;
    const gain = ctx.createGain();
    gain.gain.setValueAtTime(0, t);
    gain.gain.linearRampToValueAtTime(peak, t + 0.01);
    gain.gain.setValueAtTime(peak, t + dur * 0.7);
    gain.gain.exponentialRampToValueAtTime(1e-4, t + dur);
    src.connect(filter);
    filter.connect(gain);
    gain.connect(this.engine.output);
    src.start(t, Math.random() * 1.5);
    src.stop(t + dur + 0.05);
  }
  /** ピッチが落ちる低域の「とん」という音 */
  thump(t, from, to, dur, peak) {
    if (peak <= 0) return;
    const ctx = this.engine.context;
    const osc = ctx.createOscillator();
    osc.type = "sine";
    osc.frequency.setValueAtTime(from, t);
    osc.frequency.exponentialRampToValueAtTime(to, t + dur);
    const gain = ctx.createGain();
    gain.gain.setValueAtTime(0, t);
    gain.gain.linearRampToValueAtTime(peak, t + 4e-3);
    gain.gain.exponentialRampToValueAtTime(1e-4, t + dur);
    osc.connect(gain);
    gain.connect(this.engine.output);
    osc.start(t);
    osc.stop(t + dur + 0.05);
  }
};

// src/audio/bgm.ts
var MOODS = {
  // 雪原: Dメジャー系の明るく開けたパッド
  aurora: {
    root: 146.83,
    // D3
    chords: [
      [0, 7, 12, 16, 19],
      // D A D F# A
      [-7, 5, 9, 14],
      // Gadd9
      [-5, 2, 7, 16]
      // Asus系
    ],
    cutoff: 950,
    wind: 0.5,
    level: 1
  },
  // 夜空: Aマイナーの静かな進行
  night: {
    root: 110,
    // A2
    chords: [
      [0, 3, 7, 12],
      // Am
      [-4, 3, 8, 15],
      // F
      [-2, 5, 10, 14]
      // G
    ],
    cutoff: 680,
    wind: 0.25,
    level: 1
  },
  // 森: メジャーセブンスの温かい響き
  forest: {
    root: 130.81,
    // C3
    chords: [
      [0, 7, 11, 16],
      // Cmaj7
      [-3, 4, 7, 12],
      // Am7
      [-7, 5, 9, 12]
      // F
    ],
    cutoff: 800,
    wind: 0.35,
    level: 0.95
  },
  // 白い紙: ほとんど動かない最小限のドローン
  calm: {
    root: 174.61,
    // F3
    chords: [
      [0, 7, 12],
      [0, 5, 12]
    ],
    cutoff: 640,
    wind: 0.15,
    level: 0.7
  }
};
var BGM_MOOD_NAMES = {
  aurora: "\u30AA\u30FC\u30ED\u30E9",
  night: "\u591C",
  forest: "\u68EE",
  calm: "\u51EA"
};
var BgmPlayer = class {
  constructor(engine) {
    this.engine = engine;
    this.playing = false;
    this.mood = "calm";
    this.volume = 0.4;
    this.master = null;
    this.padBus = null;
    this.voices = [];
    this.wind = null;
    this.chordIndex = 0;
    this.timers = /* @__PURE__ */ new Set();
  }
  setVolume(v) {
    this.volume = v;
    if (this.master) {
      const t = this.engine.context.currentTime;
      this.master.gain.cancelScheduledValues(t);
      this.master.gain.setTargetAtTime(v * v, t, 0.3);
    }
  }
  start(mood) {
    if (this.playing) this.stop(0.3);
    const ctx = this.engine.context;
    this.engine.resume();
    this.mood = mood;
    const def = MOODS[mood];
    this.playing = true;
    this.master = ctx.createGain();
    this.master.gain.value = 0;
    this.master.connect(this.engine.output);
    const filter = ctx.createBiquadFilter();
    filter.type = "lowpass";
    filter.frequency.value = def.cutoff;
    filter.Q.value = 0.3;
    this.padBus = ctx.createGain();
    this.padBus.gain.value = def.level;
    this.padBus.connect(filter);
    filter.connect(this.master);
    const convolver = ctx.createConvolver();
    convolver.buffer = this.engine.createReverbImpulse(4, 2.8);
    const wet = ctx.createGain();
    wet.gain.value = 0.6;
    filter.connect(convolver);
    convolver.connect(wet);
    wet.connect(this.master);
    this.chordIndex = 0;
    this.spawnChord(def.chords[0], 6);
    this.wind = this.createWindVoice(def);
    const t = ctx.currentTime;
    this.master.gain.setValueAtTime(0, t);
    this.master.gain.linearRampToValueAtTime(this.volume * this.volume, t + 4);
    this.scheduleChordChange();
  }
  stop(fadeSeconds = 2.5) {
    this.playing = false;
    const master = this.master;
    if (!master) return;
    const voices = this.voices;
    const wind = this.wind;
    this.master = null;
    this.padBus = null;
    this.voices = [];
    this.wind = null;
    const ctx = this.engine.context;
    const t = ctx.currentTime;
    master.gain.cancelScheduledValues(t);
    master.gain.setValueAtTime(master.gain.value, t);
    master.gain.linearRampToValueAtTime(0, t + Math.max(fadeSeconds, 0.05));
    const timer = window.setTimeout(() => {
      this.timers.delete(timer);
      const all = wind ? [...voices, wind] : voices;
      for (const v of all) this.killVoice(v);
      master.disconnect();
    }, fadeSeconds * 1e3 + 150);
    this.timers.add(timer);
  }
  get currentMood() {
    return this.mood;
  }
  /** シーン切替時などにムードを入れ替える（短いフェードを挟む） */
  switchMood(mood) {
    if (this.playing && this.mood === mood) return;
    this.mood = mood;
    if (!this.playing) return;
    this.stop(1.2);
    const timer = window.setTimeout(() => {
      this.timers.delete(timer);
      this.start(mood);
    }, 1400);
    this.timers.add(timer);
  }
  dispose() {
    for (const id of this.timers) window.clearTimeout(id);
    this.timers.clear();
    this.stop(0);
  }
  // ---- 内部実装 ----
  spawnChord(offsets, fadeIn) {
    const def = MOODS[this.mood];
    const tones = [offsets[0] - 12, ...offsets];
    for (let i = 0; i < tones.length; i++) {
      const freq = def.root * Math.pow(2, tones[i] / 12);
      const isSub = i === 0;
      const level = isSub ? 0.1 : 0.07;
      this.voices.push(this.createPadVoice(freq, level, fadeIn, isSub));
    }
  }
  createPadVoice(freq, level, fadeIn, isSub) {
    const ctx = this.engine.context;
    const t = ctx.currentTime;
    const osc1 = ctx.createOscillator();
    osc1.type = isSub ? "sine" : "triangle";
    osc1.frequency.value = freq;
    const osc2 = ctx.createOscillator();
    osc2.type = "sine";
    osc2.frequency.value = freq;
    osc2.detune.value = 6;
    const gain = ctx.createGain();
    gain.gain.setValueAtTime(0, t);
    gain.gain.linearRampToValueAtTime(level, t + fadeIn * (0.8 + Math.random() * 0.4));
    const lfo = ctx.createOscillator();
    lfo.frequency.value = 0.03 + Math.random() * 0.06;
    const lfoGain = ctx.createGain();
    lfoGain.gain.value = level * 0.3;
    lfo.connect(lfoGain);
    lfoGain.connect(gain.gain);
    const pan = ctx.createStereoPanner();
    pan.pan.value = isSub ? 0 : (Math.random() * 2 - 1) * 0.5;
    osc1.connect(gain);
    osc2.connect(gain);
    gain.connect(pan);
    pan.connect(this.padBus);
    osc1.start(t);
    osc2.start(t);
    lfo.start(t);
    return { gain, tail: [gain, lfoGain, pan], sources: [osc1, osc2, lfo] };
  }
  createWindVoice(def) {
    const ctx = this.engine.context;
    const t = ctx.currentTime;
    const src = ctx.createBufferSource();
    src.buffer = this.engine.noiseBuffer;
    src.loop = true;
    const filter = ctx.createBiquadFilter();
    filter.type = "bandpass";
    filter.frequency.value = 400;
    filter.Q.value = 0.6;
    const freqLfo = ctx.createOscillator();
    freqLfo.frequency.value = 0.05;
    const freqLfoGain = ctx.createGain();
    freqLfoGain.gain.value = 180;
    freqLfo.connect(freqLfoGain);
    freqLfoGain.connect(filter.frequency);
    const gain = ctx.createGain();
    const level = def.wind * 0.06;
    gain.gain.setValueAtTime(0, t);
    gain.gain.linearRampToValueAtTime(level, t + 8);
    const ampLfo = ctx.createOscillator();
    ampLfo.frequency.value = 0.07;
    const ampLfoGain = ctx.createGain();
    ampLfoGain.gain.value = level * 0.5;
    ampLfo.connect(ampLfoGain);
    ampLfoGain.connect(gain.gain);
    src.connect(filter);
    filter.connect(gain);
    gain.connect(this.padBus);
    src.start(t);
    freqLfo.start(t);
    ampLfo.start(t);
    return { gain, tail: [gain, ampLfoGain, freqLfoGain, filter], sources: [src, freqLfo, ampLfo] };
  }
  scheduleChordChange() {
    const timer = window.setTimeout(() => {
      this.timers.delete(timer);
      if (!this.playing || !this.padBus) return;
      this.nextChord();
      this.scheduleChordChange();
    }, 22e3 + Math.random() * 14e3);
    this.timers.add(timer);
  }
  nextChord() {
    const ctx = this.engine.context;
    const def = MOODS[this.mood];
    const t = ctx.currentTime;
    const fade = 8;
    const old = this.voices;
    this.voices = [];
    for (const v of old) {
      v.gain.gain.cancelScheduledValues(t);
      v.gain.gain.setValueAtTime(v.gain.gain.value, t);
      v.gain.gain.linearRampToValueAtTime(0, t + fade);
      for (const s of v.sources) s.stop(t + fade + 0.5);
    }
    const timer = window.setTimeout(() => {
      this.timers.delete(timer);
      for (const v of old) this.killVoice(v);
    }, (fade + 1) * 1e3);
    this.timers.add(timer);
    this.chordIndex = (this.chordIndex + 1) % def.chords.length;
    this.spawnChord(def.chords[this.chordIndex], fade);
  }
  killVoice(v) {
    for (const s of v.sources) {
      try {
        s.stop();
      } catch (e) {
      }
    }
    for (const n of v.tail) n.disconnect();
  }
};

// src/ambience/particles.ts
var ParticleLayer = class {
  constructor() {
    this.canvas = null;
    this.ctx2d = null;
    this.raf = 0;
    this.items = [];
    this.kind = "snow";
    this.lastTime = 0;
    this.onResize = () => this.resize();
  }
  start(kind) {
    this.stop();
    if (kind === "none") return;
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    this.kind = kind;
    this.canvas = document.body.createEl("canvas", { cls: "calm-writer-particles" });
    this.ctx2d = this.canvas.getContext("2d");
    window.addEventListener("resize", this.onResize);
    this.resize();
    this.lastTime = performance.now();
    this.raf = window.requestAnimationFrame((t) => this.frame(t));
  }
  stop() {
    var _a;
    if (this.raf) window.cancelAnimationFrame(this.raf);
    this.raf = 0;
    window.removeEventListener("resize", this.onResize);
    (_a = this.canvas) == null ? void 0 : _a.remove();
    this.canvas = null;
    this.ctx2d = null;
    this.items = [];
  }
  resize() {
    var _a;
    if (!this.canvas) return;
    const dpr = Math.min(window.devicePixelRatio || 1, 2);
    this.canvas.width = window.innerWidth * dpr;
    this.canvas.height = window.innerHeight * dpr;
    (_a = this.ctx2d) == null ? void 0 : _a.setTransform(dpr, 0, 0, dpr, 0, 0);
    this.seed();
  }
  seed() {
    const w = window.innerWidth;
    const h = window.innerHeight;
    const density = this.kind === "stars" ? 9e3 : this.kind === "snow" ? 16e3 : 3e4;
    const n = Math.max(30, Math.min(200, Math.round(w * h / density)));
    this.items = [];
    for (let i = 0; i < n; i++) {
      this.items.push({
        x: Math.random() * w,
        y: Math.random() * h,
        r: this.kind === "stars" ? 0.5 + Math.random() * 1.2 : 0.8 + Math.random() * 2.2,
        speed: this.kind === "snow" ? 18 + Math.random() * 40 : 4 + Math.random() * 8,
        phase: Math.random() * Math.PI * 2,
        alpha: 0.3 + Math.random() * 0.5
      });
    }
  }
  frame(now) {
    if (!this.canvas || !this.ctx2d) return;
    const dt = Math.min((now - this.lastTime) / 1e3, 0.1);
    this.lastTime = now;
    const w = window.innerWidth;
    const h = window.innerHeight;
    const c = this.ctx2d;
    const t = now / 1e3;
    c.clearRect(0, 0, w, h);
    for (const p of this.items) {
      let alpha = p.alpha;
      if (this.kind === "snow") {
        p.y += p.speed * dt;
        p.x += Math.sin(t * 0.7 + p.phase) * 12 * dt;
        if (p.y > h + 4) {
          p.y = -4;
          p.x = Math.random() * w;
        }
        if (p.x > w + 4) p.x = -4;
        else if (p.x < -4) p.x = w + 4;
        c.fillStyle = "#ffffff";
      } else if (this.kind === "stars") {
        alpha = p.alpha * (0.55 + 0.45 * Math.sin(t * (0.3 + p.phase * 0.15) + p.phase));
        c.fillStyle = "#dfe6ff";
      } else {
        p.y -= p.speed * dt;
        p.x += Math.sin(t * 0.4 + p.phase) * 6 * dt;
        if (p.y < -4) {
          p.y = h + 4;
          p.x = Math.random() * w;
        }
        c.fillStyle = "#cfe8c0";
      }
      c.globalAlpha = alpha;
      c.beginPath();
      c.arc(p.x, p.y, p.r, 0, Math.PI * 2);
      c.fill();
    }
    c.globalAlpha = 1;
    this.raf = window.requestAnimationFrame((n) => this.frame(n));
  }
};

// src/ambience/zenMode.ts
var ZEN_CLASS = "calm-writer-zen";
var SCENE_CLASS_PREFIX = "calm-writer-scene-";
var ZenController = class {
  constructor(app) {
    this.app = app;
    this.active = false;
    /** このプラグインがフルスクリーンに入れたかどうか（自前で入れた時だけ抜ける） */
    this.enteredFullscreen = false;
    this.leftWasExpanded = false;
    this.rightWasExpanded = false;
  }
  enter(sceneId, fullscreen) {
    var _a, _b;
    if (this.active) return;
    this.active = true;
    document.body.classList.add(ZEN_CLASS, SCENE_CLASS_PREFIX + sceneId);
    const fade = document.body.createDiv({ cls: "calm-writer-fade" });
    window.setTimeout(() => fade.remove(), 1300);
    const ws = this.app.workspace;
    this.leftWasExpanded = ws.leftSplit ? !ws.leftSplit.collapsed : false;
    this.rightWasExpanded = ws.rightSplit ? !ws.rightSplit.collapsed : false;
    (_a = ws.leftSplit) == null ? void 0 : _a.collapse();
    (_b = ws.rightSplit) == null ? void 0 : _b.collapse();
    if (fullscreen && !document.fullscreenElement) {
      this.enteredFullscreen = true;
      document.documentElement.requestFullscreen().catch(() => {
        this.enteredFullscreen = false;
      });
    }
  }
  /** 没入モード中のシーン差し替え */
  applyScene(sceneId) {
    if (!this.active) return;
    this.removeSceneClasses();
    document.body.classList.add(SCENE_CLASS_PREFIX + sceneId);
  }
  exit() {
    var _a, _b;
    if (!this.active) return;
    this.active = false;
    document.body.classList.remove(ZEN_CLASS);
    this.removeSceneClasses();
    const ws = this.app.workspace;
    if (this.leftWasExpanded) (_a = ws.leftSplit) == null ? void 0 : _a.expand();
    if (this.rightWasExpanded) (_b = ws.rightSplit) == null ? void 0 : _b.expand();
    if (this.enteredFullscreen) {
      this.enteredFullscreen = false;
      if (document.fullscreenElement) {
        document.exitFullscreen().catch(() => {
        });
      }
    }
  }
  removeSceneClasses() {
    for (const cls of Array.from(document.body.classList)) {
      if (cls.startsWith(SCENE_CLASS_PREFIX)) document.body.classList.remove(cls);
    }
  }
};

// src/ambience/scenes.ts
var SCENES = [
  { id: "snowfield", name: "\u96EA\u539F", particles: "snow", mood: "aurora" },
  { id: "night", name: "\u591C\u7A7A", particles: "stars", mood: "night" },
  { id: "forest", name: "\u68EE", particles: "motes", mood: "forest" },
  { id: "paper", name: "\u767D\u3044\u7D19", particles: "none", mood: "calm" }
];
function getScene(id) {
  var _a;
  return (_a = SCENES.find((s) => s.id === id)) != null ? _a : SCENES[0];
}

// src/ambience/panel.ts
var ZenPanel = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.root = null;
  }
  show() {
    this.hide();
    const root = document.body.createDiv({ cls: "calm-writer-panel" });
    root.createDiv({ cls: "calm-writer-panel-hint" });
    const body = root.createDiv({ cls: "calm-writer-panel-body" });
    const scenes = this.section(body, "\u80CC\u666F");
    for (const scene of SCENES) {
      this.option(scenes, scene.name, "scene", scene.id, () => {
        void this.plugin.setScene(scene.id, false);
      });
    }
    const bgm = this.section(body, "BGM");
    this.option(bgm, "\u30B7\u30FC\u30F3\u9023\u52D5", "bgm", "auto", () => {
      void this.plugin.setBgmChoice("auto");
    });
    for (const [id, name] of Object.entries(BGM_MOOD_NAMES)) {
      this.option(bgm, name, "bgm", id, () => {
        void this.plugin.setBgmChoice(id);
      });
    }
    this.option(bgm, "\u30AA\u30D5", "bgm", "off", () => {
      void this.plugin.setBgmChoice("off");
    });
    const keys = this.section(body, "\u6253\u9375\u97F3");
    for (const [id, name] of Object.entries(KEY_SCHEMES)) {
      this.option(keys, name, "key", id, () => {
        void this.plugin.setKeySoundChoice(id);
      });
    }
    this.option(keys, "\u30AA\u30D5", "key", "off", () => {
      void this.plugin.setKeySoundChoice("off");
    });
    this.root = root;
    this.refresh();
  }
  hide() {
    var _a;
    (_a = this.root) == null ? void 0 : _a.remove();
    this.root = null;
  }
  /** 現在の設定に合わせて選択中ハイライトを付け直す */
  refresh() {
    if (!this.root) return;
    const s = this.plugin.settings;
    const active = {
      scene: s.sceneId,
      bgm: s.bgmEnabled ? s.bgmMood : "off",
      key: s.keySoundsEnabled ? s.keySoundScheme : "off"
    };
    const options = this.root.querySelectorAll(".calm-writer-panel-option");
    options.forEach((el) => {
      var _a;
      el.classList.toggle("is-active", active[(_a = el.dataset.group) != null ? _a : ""] === el.dataset.value);
    });
  }
  section(parent, title) {
    const sec = parent.createDiv({ cls: "calm-writer-panel-section" });
    sec.createDiv({ cls: "calm-writer-panel-title", text: title });
    return sec;
  }
  option(parent, label, group, value, onSelect) {
    const btn = parent.createEl("button", { cls: "calm-writer-panel-option", text: label });
    btn.dataset.group = group;
    btn.dataset.value = value;
    btn.addEventListener("mousedown", (e) => e.preventDefault());
    btn.addEventListener("click", () => {
      onSelect();
      this.refresh();
    });
  }
};

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  sceneId: "snowfield",
  fullscreen: true,
  vignette: 0.5,
  particlesEnabled: true,
  typewriterScroll: true,
  keySoundsEnabled: true,
  keySoundsEverywhere: true,
  keySoundScheme: "drop",
  keySoundVolume: 0.5,
  bgmEnabled: true,
  bgmMood: "auto",
  bgmVolume: 0.4,
  fontPreset: "",
  customFont: "",
  fontSize: 20,
  lineHeight: 2,
  editorWidth: 42
};
var FONT_PRESETS = {
  "": "\u30C6\u30FC\u30DE\u306E\u65E2\u5B9A",
  '"Hiragino Mincho ProN", "Yu Mincho", "YuMincho", "Noto Serif JP", serif': "\u660E\u671D\u4F53",
  '"Hiragino Kaku Gothic ProN", "Yu Gothic", "YuGothic", "Noto Sans JP", sans-serif': "\u30B4\u30B7\u30C3\u30AF\u4F53",
  'Georgia, "Iowan Old Style", "Times New Roman", serif': "\u6B27\u6587\u30BB\u30EA\u30D5",
  '"SF Mono", Menlo, Consolas, "Source Han Code JP", monospace': "\u7B49\u5E45"
};
var CalmWriterSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    const s = this.plugin.settings;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("\u6CA1\u5165\u30E2\u30FC\u30C9").setHeading();
    new import_obsidian.Setting(containerEl).setName("\u30B7\u30FC\u30F3").setDesc("\u80CC\u666F\u30FBBGM\u30FB\u30D1\u30FC\u30C6\u30A3\u30AF\u30EB\u306E\u7D44\u307F\u5408\u308F\u305B\u3002").addDropdown((dd) => {
      for (const scene of SCENES) dd.addOption(scene.id, scene.name);
      dd.setValue(s.sceneId).onChange(async (v) => {
        await this.plugin.setScene(v, false);
      });
    });
    new import_obsidian.Setting(containerEl).setName("\u30D5\u30EB\u30B9\u30AF\u30EA\u30FC\u30F3\u306B\u3059\u308B").setDesc("\u6CA1\u5165\u30E2\u30FC\u30C9\u958B\u59CB\u6642\u306B\u753B\u9762\u5168\u4F53\u3078\u5207\u308A\u66FF\u3048\u307E\u3059\u3002Esc\u3067\u89E3\u9664\u3067\u304D\u307E\u3059\u3002").addToggle(
      (tg) => tg.setValue(s.fullscreen).onChange(async (v) => {
        s.fullscreen = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5468\u8FBA\u6E1B\u5149\uFF08\u30D3\u30CD\u30C3\u30C8\uFF09").setDesc("\u753B\u9762\u306E\u56DB\u9685\u3092\u307B\u3093\u306E\u308A\u6697\u304F\u3057\u3066\u8996\u7DDA\u3092\u4E2D\u592E\u306B\u96C6\u3081\u307E\u3059\u3002").addSlider(
      (sl) => sl.setLimits(0, 100, 1).setValue(Math.round(s.vignette * 100)).setDynamicTooltip().onChange(async (v) => {
        s.vignette = v / 100;
        this.plugin.applyCssVars();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u30D1\u30FC\u30C6\u30A3\u30AF\u30EB").setDesc("\u96EA\u30FB\u661F\u306A\u3069\u306E\u7C92\u5B50\u6F14\u51FA\u3092\u8868\u793A\u3057\u307E\u3059\u3002").addToggle(
      (tg) => tg.setValue(s.particlesEnabled).onChange(async (v) => {
        s.particlesEnabled = v;
        this.plugin.refreshParticles();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u30BF\u30A4\u30D7\u30E9\u30A4\u30BF\u30FC\u30B9\u30AF\u30ED\u30FC\u30EB").setDesc("\u5165\u529B\u4E2D\u306E\u884C\u3092\u5E38\u306B\u753B\u9762\u306E\u4E2D\u592E\u306B\u4FDD\u3061\u307E\u3059\uFF08\u6CA1\u5165\u30E2\u30FC\u30C9\u4E2D\u306E\u307F\uFF09\u3002").addToggle(
      (tg) => tg.setValue(s.typewriterScroll).onChange(async (v) => {
        s.typewriterScroll = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u30BF\u30A4\u30D7\u97F3").setHeading();
    new import_obsidian.Setting(containerEl).setName("\u30BF\u30A4\u30D7\u97F3\u3092\u9CF4\u3089\u3059").addToggle(
      (tg) => tg.setValue(s.keySoundsEnabled).onChange(async (v) => {
        s.keySoundsEnabled = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6CA1\u5165\u30E2\u30FC\u30C9\u4EE5\u5916\u3067\u3082\u9CF4\u3089\u3059").setDesc("\u30AA\u30D5\u306B\u3059\u308B\u3068\u6CA1\u5165\u30E2\u30FC\u30C9\u4E2D\u3060\u3051\u30BF\u30A4\u30D7\u97F3\u304C\u9CF4\u308A\u307E\u3059\u3002").addToggle(
      (tg) => tg.setValue(s.keySoundsEverywhere).onChange(async (v) => {
        s.keySoundsEverywhere = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u97F3\u8272").setDesc("\u5909\u66F4\u3059\u308B\u3068\u30B5\u30F3\u30D7\u30EB\u304C\u9CF4\u308A\u307E\u3059\u3002").addDropdown((dd) => {
      for (const [id, name] of Object.entries(KEY_SCHEMES)) dd.addOption(id, name);
      dd.setValue(s.keySoundScheme).onChange(async (v) => {
        s.keySoundScheme = v;
        this.plugin.applyAudioSettings();
        this.plugin.keySounds.play("key");
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("\u30BF\u30A4\u30D7\u97F3\u306E\u97F3\u91CF").addSlider(
      (sl) => sl.setLimits(0, 100, 1).setValue(Math.round(s.keySoundVolume * 100)).setDynamicTooltip().onChange(async (v) => {
        s.keySoundVolume = v / 100;
        this.plugin.applyAudioSettings();
        this.plugin.keySounds.play("key");
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("BGM").setHeading();
    new import_obsidian.Setting(containerEl).setName("\u6CA1\u5165\u30E2\u30FC\u30C9\u3067BGM\u3092\u6D41\u3059").setDesc("\u30B7\u30FC\u30F3\u306B\u5408\u308F\u305B\u305F\u30A2\u30F3\u30D3\u30A8\u30F3\u30C8\u3092\u81EA\u52D5\u518D\u751F\u3057\u307E\u3059\u3002\u30B3\u30DE\u30F3\u30C9\u3067\u5358\u72EC\u518D\u751F\u3082\u3067\u304D\u307E\u3059\u3002").addToggle(
      (tg) => tg.setValue(s.bgmEnabled).onChange(async (v) => {
        s.bgmEnabled = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("BGM\u306E\u30E0\u30FC\u30C9").setDesc("\u300C\u30B7\u30FC\u30F3\u9023\u52D5\u300D\u306F\u30B7\u30FC\u30F3\u306B\u5408\u308F\u305B\u3066\u81EA\u52D5\u3067\u9078\u3073\u307E\u3059\u3002").addDropdown((dd) => {
      dd.addOption("auto", "\u30B7\u30FC\u30F3\u9023\u52D5");
      for (const [id, name] of Object.entries(BGM_MOOD_NAMES)) dd.addOption(id, name);
      dd.setValue(s.bgmMood).onChange(async (v) => {
        s.bgmMood = v;
        if (this.plugin.bgm.playing) {
          this.plugin.bgm.switchMood(this.plugin.effectiveMood());
        }
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("BGM\u306E\u97F3\u91CF").addSlider(
      (sl) => sl.setLimits(0, 100, 1).setValue(Math.round(s.bgmVolume * 100)).setDynamicTooltip().onChange(async (v) => {
        s.bgmVolume = v / 100;
        this.plugin.applyAudioSettings();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6587\u5B57\u3068\u4F59\u767D\uFF08\u6CA1\u5165\u30E2\u30FC\u30C9\u4E2D\uFF09").setHeading();
    new import_obsidian.Setting(containerEl).setName("\u30D5\u30A9\u30F3\u30C8").addDropdown((dd) => {
      for (const [value, name] of Object.entries(FONT_PRESETS)) dd.addOption(value, name);
      dd.setValue(s.fontPreset in FONT_PRESETS ? s.fontPreset : "").onChange(async (v) => {
        s.fontPreset = v;
        this.plugin.applyCssVars();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("\u30AB\u30B9\u30BF\u30E0\u30D5\u30A9\u30F3\u30C8").setDesc("CSS\u306Efont-family\u5F62\u5F0F\u3002\u5165\u529B\u3059\u308B\u3068\u30D7\u30EA\u30BB\u30C3\u30C8\u3088\u308A\u512A\u5148\u3055\u308C\u307E\u3059\u3002").addText(
      (tx) => tx.setPlaceholder('"Klee One", serif').setValue(s.customFont).onChange(async (v) => {
        s.customFont = v;
        this.plugin.applyCssVars();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6587\u5B57\u30B5\u30A4\u30BA").addSlider(
      (sl) => sl.setLimits(14, 30, 1).setValue(s.fontSize).setDynamicTooltip().onChange(async (v) => {
        s.fontSize = v;
        this.plugin.applyCssVars();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u884C\u306E\u9AD8\u3055").addSlider(
      (sl) => sl.setLimits(1.4, 2.8, 0.1).setValue(s.lineHeight).setDynamicTooltip().onChange(async (v) => {
        s.lineHeight = v;
        this.plugin.applyCssVars();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u672C\u6587\u306E\u5E45").setDesc("\u5358\u4F4D: rem\u3002\u5C0F\u3055\u3044\u307B\u30691\u884C\u304C\u77ED\u304F\u306A\u308A\u307E\u3059\u3002").addSlider(
      (sl) => sl.setLimits(28, 60, 1).setValue(s.editorWidth).setDynamicTooltip().onChange(async (v) => {
        s.editorWidth = v;
        this.plugin.applyCssVars();
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/main.ts
var CSS_VARS = [
  "--calm-font-family",
  "--calm-font-size",
  "--calm-line-height",
  "--calm-editor-width",
  "--calm-vignette"
];
var CalmWriterPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.engine = new AudioEngine();
    this.keySounds = new KeySoundPlayer(this.engine);
    this.bgm = new BgmPlayer(this.engine);
    this.particles = new ParticleLayer();
    this.panel = new ZenPanel(this);
  }
  async onload() {
    await this.loadSettings();
    this.zen = new ZenController(this.app);
    this.applyAudioSettings();
    this.applyCssVars();
    this.addRibbonIcon("mountain-snow", "\u6CA1\u5165\u30E2\u30FC\u30C9\u3092\u5207\u308A\u66FF\u3048", () => this.toggleZen());
    this.addCommand({
      id: "toggle-zen",
      name: "\u6CA1\u5165\u30E2\u30FC\u30C9\u3092\u5207\u308A\u66FF\u3048",
      callback: () => this.toggleZen()
    });
    this.addCommand({
      id: "toggle-key-sounds",
      name: "\u30BF\u30A4\u30D7\u97F3\u306E\u30AA\u30F3/\u30AA\u30D5",
      callback: async () => {
        this.settings.keySoundsEnabled = !this.settings.keySoundsEnabled;
        await this.saveSettings();
        new import_obsidian2.Notice(this.settings.keySoundsEnabled ? "\u30BF\u30A4\u30D7\u97F3: \u30AA\u30F3" : "\u30BF\u30A4\u30D7\u97F3: \u30AA\u30D5");
      }
    });
    this.addCommand({
      id: "toggle-bgm",
      name: "BGM\u306E\u518D\u751F/\u505C\u6B62",
      callback: () => this.toggleBgm()
    });
    this.addCommand({
      id: "next-scene",
      name: "\u6B21\u306E\u30B7\u30FC\u30F3\u3078\u5207\u308A\u66FF\u3048",
      callback: async () => {
        const idx = SCENES.findIndex((sc) => sc.id === this.settings.sceneId);
        const next = SCENES[(idx + 1) % SCENES.length];
        await this.setScene(next.id, true);
      }
    });
    this.registerDomEvent(document, "keydown", (e) => this.onKeyDown(e), { capture: true });
    this.registerDomEvent(document, "fullscreenchange", () => {
      if (this.zen.active && this.zen.enteredFullscreen && !document.fullscreenElement) {
        this.exitZen();
      }
    });
    this.registerEditorExtension(this.typewriterExtension());
    this.addSettingTab(new CalmWriterSettingTab(this.app, this));
  }
  onunload() {
    this.exitZen();
    this.bgm.dispose();
    this.particles.stop();
    this.engine.dispose();
    for (const v of CSS_VARS) document.body.style.removeProperty(v);
  }
  // ---- 没入モード ----
  toggleZen() {
    if (this.zen.active) this.exitZen();
    else this.enterZen();
  }
  enterZen() {
    const scene = getScene(this.settings.sceneId);
    this.zen.enter(scene.id, this.settings.fullscreen);
    if (this.settings.particlesEnabled) this.particles.start(scene.particles);
    if (this.settings.bgmEnabled && !this.bgm.playing) this.bgm.start(this.effectiveMood());
    this.panel.show();
    this.engine.resume();
  }
  exitZen() {
    if (!this.zen.active) return;
    this.zen.exit();
    this.panel.hide();
    this.particles.stop();
    this.bgm.stop();
  }
  /** シーンを保存し、没入モード中なら見た目と音を即座に反映する */
  async setScene(sceneId, notify) {
    this.settings.sceneId = sceneId;
    await this.saveSettings();
    const scene = getScene(sceneId);
    if (this.zen.active) {
      this.zen.applyScene(scene.id);
      this.refreshParticles();
      if (this.bgm.playing && this.settings.bgmMood === "auto") {
        this.bgm.switchMood(scene.mood);
      }
    }
    this.panel.refresh();
    if (notify) new import_obsidian2.Notice(`\u30B7\u30FC\u30F3: ${scene.name}`);
  }
  refreshParticles() {
    if (!this.zen.active) return;
    if (this.settings.particlesEnabled) {
      this.particles.start(getScene(this.settings.sceneId).particles);
    } else {
      this.particles.stop();
    }
  }
  // ---- 音 ----
  toggleBgm() {
    if (this.bgm.playing) {
      this.bgm.stop();
      new import_obsidian2.Notice("BGM\u3092\u505C\u6B62\u3057\u307E\u3057\u305F");
    } else {
      this.bgm.start(this.effectiveMood());
      new import_obsidian2.Notice("BGM\u3092\u518D\u751F\u3057\u307E\u3059");
    }
  }
  /** BGMのムード設定（シーン連動 or 固定）を実際のムードに解決する */
  effectiveMood() {
    return this.settings.bgmMood === "auto" ? getScene(this.settings.sceneId).mood : this.settings.bgmMood;
  }
  /** パネルからのBGM切り替え。オフ以外を選ぶと再生も始める */
  async setBgmChoice(choice) {
    if (choice === "off") {
      this.settings.bgmEnabled = false;
      this.bgm.stop();
    } else {
      this.settings.bgmEnabled = true;
      this.settings.bgmMood = choice;
      const mood = this.effectiveMood();
      if (this.bgm.playing) this.bgm.switchMood(mood);
      else this.bgm.start(mood);
    }
    await this.saveSettings();
    this.panel.refresh();
  }
  /** パネルからの打鍵音切り替え。音色を選ぶとサンプルを鳴らす */
  async setKeySoundChoice(choice) {
    if (choice === "off") {
      this.settings.keySoundsEnabled = false;
    } else {
      this.settings.keySoundsEnabled = true;
      this.settings.keySoundScheme = choice;
      this.applyAudioSettings();
      this.keySounds.play("key");
    }
    await this.saveSettings();
    this.panel.refresh();
  }
  applyAudioSettings() {
    this.keySounds.volume = this.settings.keySoundVolume;
    this.keySounds.scheme = this.settings.keySoundScheme;
    this.bgm.setVolume(this.settings.bgmVolume);
  }
  onKeyDown(e) {
    const s = this.settings;
    if (!s.keySoundsEnabled) return;
    if (!this.zen.active && !s.keySoundsEverywhere) return;
    if (e.ctrlKey || e.metaKey || e.altKey) return;
    const target = e.target;
    if (!(target instanceof HTMLElement)) return;
    if (!target.closest(".cm-editor, .inline-title")) return;
    const kind = classifyKey(e);
    if (kind) this.keySounds.play(kind, e.code);
  }
  // ---- 表示 ----
  applyCssVars() {
    const s = this.settings;
    const st = document.body.style;
    const font = s.customFont.trim() || s.fontPreset || "inherit";
    st.setProperty("--calm-font-family", font);
    st.setProperty("--calm-font-size", `${s.fontSize}px`);
    st.setProperty("--calm-line-height", String(s.lineHeight));
    st.setProperty("--calm-editor-width", `${s.editorWidth}rem`);
    st.setProperty("--calm-vignette", String(s.vignette));
  }
  /** 入力した行を画面中央に保つCodeMirror拡張（没入モード中のみ動く） */
  typewriterExtension() {
    return import_view.EditorView.updateListener.of((update) => {
      if (!update.docChanged) return;
      if (!this.zen.active || !this.settings.typewriterScroll) return;
      if (!update.view.hasFocus) return;
      const view = update.view;
      window.requestAnimationFrame(() => {
        try {
          view.dispatch({
            effects: import_view.EditorView.scrollIntoView(view.state.selection.main.head, {
              y: "center"
            })
          });
        } catch (e) {
        }
      });
    });
  }
  // ---- 設定 ----
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
function classifyKey(e) {
  if (e.key === "Enter") {
    return e.isComposing || e.keyCode === 229 ? "enter" : "return";
  }
  if (e.key === " " || e.key === "Spacebar") return "space";
  if (e.key === "Backspace" || e.key === "Delete") return "delete";
  if (e.key === "Process" || e.isComposing) return "key";
  if (e.key.length === 1) return "key";
  return null;
}
